#!/bin/bash
#
# ╔══════════════════════════════════════════════════════════════╗
# ║  Ligend VPN — One-Line Installer by GOmp Studios            ║
# ║  Usage: bash <(curl -Ls https://raw.githubusercontent.com/  ║
# ║         ligend/install/main/install.sh)                     ║
# ╚══════════════════════════════════════════════════════════════╝
#
set -euo pipefail

# ── Colors ──
RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
PURPLE='\033[0;35m'
BOLD='\033[1m'
NC='\033[0m'

LIGEND_VERSION="3.5.0"
INSTALL_DIR="/etc/ligend"
BIN_DIR="/usr/local/bin"
SERVICE_FILE="/etc/systemd/system/ligend.service"
BINARY_URL="https://github.com/ZakharKutikov/ligend/releases/latest/download/ligend-server-linux-amd64"

# ── Helpers ──
info()  { echo -e "${CYAN}[INFO]${NC}  $1"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $1"; }
fail()  { echo -e "${RED}[FAIL]${NC}  $1"; exit 1; }

banner() {
    echo -e "${PURPLE}"
    echo "  ╔════════════════════════════════════════════╗"
    echo "  ║   ⚡  Ligend VPN Installer v${LIGEND_VERSION}         ║"
    echo "  ║   by GOmp Studios                         ║"
    echo "  ╚════════════════════════════════════════════╝"
    echo -e "${NC}"
}

# ── Pre-flight checks ──
preflight() {
    if [[ $EUID -ne 0 ]]; then
        fail "Запустите от root: sudo bash install.sh"
    fi

    if ! command -v apt-get &>/dev/null; then
        fail "Поддерживаются только Ubuntu 20+ / Debian 11+"
    fi

    ARCH=$(uname -m)
    if [[ "$ARCH" != "x86_64" && "$ARCH" != "amd64" ]]; then
        fail "Поддерживается только amd64 (x86_64), у вас: $ARCH"
    fi

    info "Система: $(lsb_release -ds 2>/dev/null || cat /etc/os-release | grep PRETTY_NAME | cut -d= -f2 | tr -d '\"') ($ARCH)"
}

# ── Install dependencies ──
install_deps() {
    info "Установка зависимостей..."
    
    # Kill any stale apt processes & locks
    rm -f /var/lib/apt/lists/lock /var/cache/apt/archives/lock /var/lib/dpkg/lock* 2>/dev/null || true

    # Pre-seed iptables-persistent to avoid interactive debconf prompts hanging
    echo iptables-persistent iptables-persistent/autosave_v4 boolean true | debconf-set-selections 2>/dev/null || true
    echo iptables-persistent iptables-persistent/autosave_v6 boolean true | debconf-set-selections 2>/dev/null || true

    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y -q
    apt-get install -y -q -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
        curl wget nginx certbot python3-certbot-nginx iptables iptables-persistent net-tools
    ok "Зависимости установлены"
}

# ── Download binary ──
download_binary() {
    info "Подготовка Ligend Server v${LIGEND_VERSION}..."
    mkdir -p "${BIN_DIR}"

    # 1. Check if binary already in /usr/local/bin
    if [[ -f "${BIN_DIR}/ligend-server" ]] && [[ -x "${BIN_DIR}/ligend-server" ]]; then
        ok "Используется установленный бинарник: ${BIN_DIR}/ligend-server"
        return 0
    fi

    # 2. Check current directory
    if [[ -f "./ligend-server-linux" ]]; then
        cp "./ligend-server-linux" "${BIN_DIR}/ligend-server"
        chmod +x "${BIN_DIR}/ligend-server"
        ok "Бинарник скопирован из текущей папки: ${BIN_DIR}/ligend-server"
        return 0
    fi

    # 3. Check /root/ligend-server-linux
    if [[ -f "/root/ligend-server-linux" ]]; then
        cp "/root/ligend-server-linux" "${BIN_DIR}/ligend-server"
        chmod +x "${BIN_DIR}/ligend-server"
        ok "Бинарник скопирован из /root: ${BIN_DIR}/ligend-server"
        return 0
    fi

    # 4. Try downloading from GitHub
    info "Попытка скачивания с GitHub..."
    if curl -fsSL --connect-timeout 10 -o "${BIN_DIR}/ligend-server" "${BINARY_URL}" 2>/dev/null; then
        chmod +x "${BIN_DIR}/ligend-server"
        ok "Бинарник скачан с GitHub: ${BIN_DIR}/ligend-server"
        return 0
    fi

    fail "Бинарник ligend-server не найден на сервере! Загрузите его: scp server/ligend-server-linux root@$(hostname -I | awk '{print $1}'):/usr/local/bin/ligend-server"
}

# ── Generate keys ──
generate_keys() {
    SECRET_KEY=$(openssl rand -base64 32)
    WS_PATH="/ws-$(openssl rand -hex 8)"
    ok "Ключи сгенерированы"
}

# ── Create config files ──
create_config() {
    info "Создание конфигурации..."

    mkdir -p "${INSTALL_DIR}/panel"
    mkdir -p "${INSTALL_DIR}/web"

    # Main config
    cat > "${INSTALL_DIR}/ligend.yaml" <<EOF
# Ligend VPN Server Configuration
# Generated by GOmp Studios Installer v${LIGEND_VERSION}
# $(date -Iseconds)

listen_addr: ":8443"
udp_port: 51820
game_mode: true
ws_path: "${WS_PATH}"
secret_key: "${SECRET_KEY}"
vpn_subnet: "10.8.0.0/24"
tun_name: "ligend0"
mtu: 1280
dns:
  - "1.1.1.1"
  - "8.8.8.8"
web_root: "${INSTALL_DIR}/web"
padding_min_sec: 3
padding_max_sec: 15
max_clients: 254
awg_jc: 4
awg_jmin: 40
awg_jmax: 70
EOF
    chmod 600 "${INSTALL_DIR}/ligend.yaml"

    # Cover website (decoy)
    if [[ ! -f "${INSTALL_DIR}/web/index.html" ]]; then
        cat > "${INSTALL_DIR}/web/index.html" <<'WEBEOF'
<!DOCTYPE html><html><head><meta charset="utf-8"><title>CloudDev Notes</title>
<style>body{font-family:system-ui;max-width:800px;margin:50px auto;padding:20px;color:#333;line-height:1.6}
h1{color:#1a73e8}a{color:#1a73e8}.post{border-bottom:1px solid #eee;padding:20px 0}</style></head>
<body><h1>CloudDev Notes</h1><p>Блог о технологиях и облачной разработке</p>
<div class="post"><h2>Kubernetes Best Practices 2026</h2><p>Обзор лучших практик для production кластеров...</p></div>
<div class="post"><h2>Оптимизация PostgreSQL</h2><p>Тюнинг запросов и индексов для высоконагруженных проектов...</p></div>
<div class="post"><h2>CI/CD с GitHub Actions</h2><p>Автоматизация деплоя через GitHub Actions и ArgoCD...</p></div>
<footer style="margin-top:40px;color:#999">&copy; 2026 CloudDev Notes. All rights reserved.</footer></body></html>
WEBEOF
    fi

    # Panel HTML — embed if exists in script directory, otherwise download
    if [[ -f "panel/index.html" ]]; then
        cp "panel/index.html" "${INSTALL_DIR}/panel/index.html"
    elif [[ -f "/tmp/ligend-panel/index.html" ]]; then
        cp "/tmp/ligend-panel/index.html" "${INSTALL_DIR}/panel/index.html"
    fi

    ok "Конфигурация создана: ${INSTALL_DIR}/ligend.yaml"
}

# ── Setup networking ──
setup_network() {
    info "Настройка сети..."

    # Enable IP forwarding
    sysctl -w net.ipv4.ip_forward=1 > /dev/null
    echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/99-ligend.conf
    sysctl -p /etc/sysctl.d/99-ligend.conf > /dev/null 2>&1

    # NAT masquerade
    DEFAULT_IFACE=$(ip route show default | awk '/default/ {print $5}' | head -1)
    if [[ -n "$DEFAULT_IFACE" ]]; then
        iptables -t nat -C POSTROUTING -s 10.8.0.0/24 -o "$DEFAULT_IFACE" -j MASQUERADE 2>/dev/null || \
        iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o "$DEFAULT_IFACE" -j MASQUERADE
        ok "NAT настроен на интерфейсе $DEFAULT_IFACE"
    else
        warn "Не удалось определить сетевой интерфейс, настройте NAT вручную"
    fi

    # Save iptables
    iptables-save > /etc/iptables/rules.v4 2>/dev/null || true

    # UFW (if installed)
    if command -v ufw &>/dev/null; then
        ufw allow 80/tcp > /dev/null 2>&1 || true
        ufw allow 443/tcp > /dev/null 2>&1 || true
        ufw allow 51820/udp > /dev/null 2>&1 || true
        ufw allow 8443/tcp > /dev/null 2>&1 || true
    fi

    ok "Сеть настроена"
}

# ── Setup Nginx ──
setup_nginx() {
    DOMAIN=""
    VPS_IP=$(curl -s4 ifconfig.me 2>/dev/null || curl -s4 icanhazip.com 2>/dev/null || hostname -I | awk '{print $1}')

    echo ""
    echo -e "${BOLD}Настройка домена${NC}"
    echo -e "  Введите домен (например: vpn.example.com)"
    echo -e "  Или нажмите ${CYAN}[Enter]${NC} для работы без домена (по IP)"
    echo -n "  Домен: "
    read -r DOMAIN

    if [[ -n "$DOMAIN" ]]; then
        info "Настройка Nginx с SSL для ${DOMAIN}..."

        cat > /etc/nginx/sites-available/ligend <<EOF
server {
    listen 80;
    server_name ${DOMAIN};
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ${DOMAIN};

    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_session_cache shared:SSL:10m;

    location ${WS_PATH} {
        proxy_pass http://127.0.0.1:8443;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_buffering off;
        proxy_cache off;
    }

    location / {
        proxy_pass http://127.0.0.1:8443;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }
}
EOF
        ln -sf /etc/nginx/sites-available/ligend /etc/nginx/sites-enabled/ligend
        rm -f /etc/nginx/sites-enabled/default

        # Get SSL certificate
        certbot --nginx -d "${DOMAIN}" --non-interactive --agree-tos --register-unsafely-without-email 2>/dev/null || \
        certbot certonly --standalone -d "${DOMAIN}" --non-interactive --agree-tos --register-unsafely-without-email 2>/dev/null || \
        warn "Не удалось получить SSL сертификат. Настройте вручную: certbot --nginx -d ${DOMAIN}"

        nginx -t > /dev/null 2>&1 && systemctl restart nginx
        ok "Nginx + SSL настроен для ${DOMAIN}"
    else
        info "Работа без домена (прямое подключение по IP:8443)"
        # Remove default nginx site to free port 80
        rm -f /etc/nginx/sites-enabled/default
        systemctl stop nginx 2>/dev/null || true
        systemctl disable nginx 2>/dev/null || true
        ok "Nginx отключен (прямое подключение)"
    fi
}

# ── Install systemd service ──
install_service() {
    info "Установка systemd сервиса..."

    cat > "${SERVICE_FILE}" <<EOF
[Unit]
Description=Ligend VPN Server (GOmp Studios)
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=root
Group=root
ExecStart=${BIN_DIR}/ligend-server -config ${INSTALL_DIR}/ligend.yaml
Restart=always
RestartSec=5
LimitNOFILE=65536
LimitNPROC=4096

StandardOutput=journal
StandardError=journal
SyslogIdentifier=ligend

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable ligend > /dev/null 2>&1
    systemctl restart ligend

    # Wait for panel to start
    sleep 3

    ok "Сервис ligend.service установлен и запущен"
}

# ── Get panel port from logs ──
get_panel_port() {
    PANEL_PORT=$(journalctl -u ligend -n 20 --no-pager 2>/dev/null | grep -oP 'URL: http://0\.0\.0\.0:\K[0-9]+' | tail -1)
    if [[ -z "$PANEL_PORT" ]]; then
        PANEL_PORT="(см. journalctl -u ligend)"
    fi
}

# ── Print summary ──
print_summary() {
    get_panel_port

    echo ""
    echo -e "${GREEN}"
    echo "  ╔══════════════════════════════════════════════════════════╗"
    echo "  ║         ⚡ GOmp Studios — Ligend v${LIGEND_VERSION} Installed!       ║"
    echo "  ╠══════════════════════════════════════════════════════════╣"
    echo "  ║                                                          ║"
    echo "  ║  📊 Панель управления:                                   ║"
    echo "  ║     http://${VPS_IP}:${PANEL_PORT}                       "
    echo "  ║     Логин: admin / admin                                 ║"
    echo "  ║                                                          ║"
    echo "  ║  🔒 VPN подключение:                                     ║"
    if [[ -n "$DOMAIN" ]]; then
    echo "  ║     Сервер:  ${DOMAIN}                                   "
    else
    echo "  ║     Сервер:  ${VPS_IP}                                   "
    fi
    echo "  ║     Порт:    443 (WSS) + 51820 (UDP Gaming)             ║"
    echo "  ║     WS Path: ${WS_PATH}                                  "
    echo "  ║                                                          ║"
    echo "  ║  🔑 Секретный ключ (для Android):                        ║"
    echo "  ║     ${SECRET_KEY}  "
    echo "  ║                                                          ║"
    echo "  ╠══════════════════════════════════════════════════════════╣"
    echo "  ║  Команды:                                                ║"
    echo "  ║    systemctl status ligend   — статус                    ║"
    echo "  ║    systemctl restart ligend  — перезапуск                ║"
    echo "  ║    journalctl -u ligend -f   — логи                     ║"
    echo "  ║    bash /etc/ligend/uninstall.sh — удаление              ║"
    echo "  ╚══════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

# ── Main ──
main() {
    banner
    preflight
    install_deps
    download_binary
    generate_keys
    create_config
    setup_network
    setup_nginx
    install_service
    print_summary
}

main "$@"
